<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 3.1 (Python 3.6.8 on darwin)" generated="20200928 15:27:33.432" rpa="false">
<suite id="s1" name="Comparator" source="/Users/sameem/Desktop/Sameem/python_practice/weathercomparator/test/comparator.robot">
<test id="s1-t1" name="Test the comparator">
<kw name="Compare Temperature For">
<arguments>
<arg>Bengaluru</arg>
<arg>IN</arg>
</arguments>
<msg timestamp="20200928 15:27:33.716" level="FAIL">No keyword with name 'Compare Temperature For' found.</msg>
<status status="FAIL" starttime="20200928 15:27:33.716" endtime="20200928 15:27:33.716"></status>
</kw>
<status status="FAIL" starttime="20200928 15:27:33.713" endtime="20200928 15:27:33.717" critical="yes">No keyword with name 'Compare Temperature For' found.</status>
</test>
<status status="FAIL" starttime="20200928 15:27:33.433" endtime="20200928 15:27:33.717"></status>
</suite>
<statistics>
<total>
<stat pass="0" fail="1">Critical Tests</stat>
<stat pass="0" fail="1">All Tests</stat>
</total>
<tag>
</tag>
<suite>
<stat pass="0" fail="1" id="s1" name="Comparator">Comparator</stat>
</suite>
</statistics>
<errors>
<msg timestamp="20200928 15:27:33.712" level="ERROR">Error in file '/Users/sameem/Desktop/Sameem/python_practice/weathercomparator/test/comparator.robot': Initializing test library 'comparator' with no arguments failed: FileNotFoundError: [Errno 2] No such file or directory: 'config/config.json'
Traceback (most recent call last):
  File "/Users/sameem/Desktop/Sameem/python_practice/weathercomparator/comparator.py", line 17, in __init__
    with open('config/config.json') as config_file:</msg>
</errors>
</robot>
